feat/whitelistadmin
EngineerProOrg/EP-FYI pull request #32
Opened 2024-06-04 12:06 UTC by ducnd58233

2024-06-05 04:33 UTC, tranHieuDev23 requested changes

2024-06-05 04:33 UTC, tranHieuDev23 commented on offer_service/Makefile
> +test-coverage:
Tách lệnh `make test-coverage` thành hai lệnh riêng `make test` và `make cover`. `make cover` chỉ làm nhiệm vụ `go tool cover` thôi, sử dụng kết quả từ `make test`.

2024-06-05 04:33 UTC, tranHieuDev23 commented on offer_service/configs/configs.yaml
> +white_listed_admin_account:
Sửa thành `whitelisted_admin_emails`, và array này chỉ cần là 1 array string là đủ

2024-06-05 04:33 UTC, tranHieuDev23 commented on offer_service/internal/handlers/grpc/handler.go
> +func (h Handler) getAccountEmailFromMetadata(ctx context.Context) string {
Đẩy logic `getAccountEmailFromMetadata` này vào trong business logic:
1. Handler sẽ lấy token từ context.
2. Handler pass token + input cho request vào trong logic.
3. Logic lấy email từ token và kiểm tra xem email có được whitelist hay không.

2024-06-05 04:38 UTC, ducnd58233 commented on offer_service/Makefile
> +test-coverage:
cái `make test` và `make test-coverage` hiện tại em làm thì cái test nó không xuất file coverage, còn cái thứ 2 thì xuất luôn file coverage ạ

2024-06-06 20:40 UTC, tranHieuDev23 requested changes

2024-06-06 20:40 UTC, tranHieuDev23 commented on offer_service/internal/handlers/grpc/clients/account_core/client.go
> +type Client interface {
Interface này giống hệt như interface được generate ra bởi gRPC, do đó không cần phải khai báo lại. Em có thể cài đặt một struct khác tuân thủ theo interface được sinh ra sẵn đó.

2024-06-06 20:40 UTC, tranHieuDev23 commented on offer_service/internal/handlers/grpc/clients/account_core/client.go
> +type randomClient struct {
Đổi tên struct này thành `compositeClient`, vì đây là client tổng hợp nhiều client con.

2024-06-06 20:40 UTC, tranHieuDev23 commented on offer_service/internal/handlers/grpc/clients/account_core/client.go
> +type RandomIndexFunc func(int) (int, error)
1. Đặt tên cho các giá trị input và output của `RandomIndexFunc`.
2. Thật ra nên đổi type này thành `RandomIntFunc(max int) (output int, err error)` vì nó là hàm random có thể sử dụng cho tác vụ bất kì, không chỉ là dành cho index,

2024-06-06 20:40 UTC, tranHieuDev23 commented on offer_service/internal/logic/offer_management.go
>  type OfferManagement interface {
1. Bổ sung thêm cơ chế check whitelist cho các function `CreateCompany`, `UpdateCompany`, `CreateCompanyProfileImage`.
2. Hàm `getAccountEmailFromMetadata()` có thể để ở ngoài handler layer, thông tin account (bao gồm email) đang thực hiện các tác vụ này có thể bỏ vào trong `CreateCompanyParams`, `UpdateCompanyParams`, etc... Điều này giúp tuyên bố rõ ràng rằng thông tin người dùng (mà quan trọng ở đây là email) là một thành phần phải có trong input vào các business logic này, dù input có là HTTP, gRPC hay Kafka. Nó cũng giúp cho logic ở phần business logic tránh bị vòng vào phụ thuộc trực tiếp vào gRPC ở handler.

2024-06-07 01:54 UTC, ducnd58233 commented on offer_service/internal/handlers/grpc/clients/account_core/client.go
> +type Client interface {
cái interface này để generate ra mock file ạ, em generate xong em lỡ xóa mất cái lệnh generate, chứ không có interface này thì làm sao mình có mock của cái client này ạ?

2024-06-07 02:11 UTC, ducnd58233 commented on offer_service/internal/logic/offer_management.go
>  type OfferManagement interface {
CreateCompany, UpdateCompany, CreateCompanyProfileImage em nghĩ mấy cái function này không cần whitelist chứ ạ? Tại vì ví dụ user có 1 cái offer của 1 company chưa có trong database thì sao anh nhỉ?

2024-06-07 02:13 UTC, ducnd58233 commented on offer_service/internal/logic/offer_management.go
>  type OfferManagement interface {
Cái ý thứ 2 của anh có nghĩa là mình nên bỏ cả cái Account vào Params ạ? Nhưng mà ở handler mình đâu trích xuất metadata đâu mà cần bỏ thông tin đó vào Params ạ?

2024-06-09 20:05 UTC, tranHieuDev23 approved these changes

2024-06-09 20:05 UTC, merged